// Canonical id -> label map for the built-in real-estate scenarios.
// Auto-generated from backend/src/authoring/taxonomy.py. Last-resort fallback so
// the Review page never shows raw ids, even for orphaned/old attempts.

export const TAXONOMY_LABELS: Record<string, string> = {
  "stage-1": "Concept & Acquisition",
  "proc-stage-1": "Concept & Acquisition",
  "stage-2": "Pre-Development Due Diligence & Planning",
  "proc-stage-2": "Pre-Development Due Diligence & Planning",
  "stage-3": "Design",
  "proc-stage-3": "Design",
  "stage-4": "Entitlements & Jurisdictional Approvals",
  "proc-stage-4": "Entitlements & Jurisdictional Approvals",
  "stage-5": "Financing",
  "proc-stage-5": "Financing",
  "stage-6": "Development/Construction",
  "proc-stage-6": "Development/Construction",
  "stage-7": "Sales/Leasing",
  "proc-stage-7": "Sales/Leasing",
  "stage-8": "Operations/Property Management",
  "proc-stage-8": "Operations/Property Management",
  "act-1": "Market Analysis & Development Concept",
  "act-2": "Site Identification & Acquisition Strategy",
  "act-3": "Preliminary Feasibility & Underwriting",
  "act-4": "Site Due Diligence",
  "act-5": "Acquisition & Pre-Development Financing",
  "act-6": "Planning, Programming & Concept Design",
  "act-7": "Zoning, Entitlements & Public Approvals",
  "act-8": "Design & Engineering",
  "act-9": "Development & Construction Financing",
  "act-10": "Permitting & Preconstruction",
  "act-11": "Construction & Development Management",
  "act-12": "Marketing, Leasing & Sales",
  "act-13": "Completion, Commissioning & Jurisdictional Acceptance",
  "act-14": "Operations, Property Management & Asset Management",
  "act-15": "Stabilization, Refinance & Disposition",
  "pro-developer": "Developer / Owner",
  "pro-devmgr": "Development Manager",
  "pro-acqmgr": "Acquisition Manager",
  "pro-finanalyst": "Financial Analyst",
  "pro-market": "Market Research Consultant",
  "pro-broker": "Land / Investment Broker",
  "pro-reattorney": "Real Estate Attorney",
  "pro-luattorney": "Land-Use Attorney",
  "pro-title": "Title / Escrow Company",
  "pro-surveyor": "Surveyor",
  "pro-environmental": "Environmental Consultant",
  "pro-geotech": "Geotechnical Engineer",
  "pro-civil": "Civil Engineer",
  "pro-traffic": "Traffic Engineer",
  "pro-planner": "Land Planner",
  "pro-architect": "Architect",
  "pro-landscape": "Landscape Architect",
  "pro-structmep": "Structural / MEP Engineers",
  "pro-costest": "Cost Estimator",
  "pro-gc": "General Contractor",
  "pro-ownerrep": "Owner's Representative / Construction Manager",
  "pro-lender": "Construction Lender / Mortgage Banker",
  "pro-equity": "Equity Investor / JV Partner",
  "pro-appraiser": "Appraiser",
  "pro-cpa": "CPA / Tax Advisor",
  "pro-marketing": "Marketing Agency",
  "pro-leasing": "Leasing / Sales Broker or Agent",
  "pro-pm": "Property Manager",
  "pro-am": "Asset Manager",
  "pro-commissioning": "Commissioning Agent",
  "pro-officials": "Building / Jurisdiction Officials",
  "task-marketstudy": "Market Study / Concept Test",
  "task-siteloi": "Site Search & LOI / Site Control",
  "task-proforma": "Development Pro Forma",
  "task-ddreports": "Title, Survey & Environmental Reports",
  "task-closingdocs": "Purchase & Closing Documentation",
  "task-conceptplan": "Concept Site Plan / Yield Study",
  "task-entitlementapp": "Entitlement Application & Traffic Study",
  "task-constrdocs": "Schematic Design \u2192 Construction Documents",
  "task-capitalstack": "Sources & Uses / Capital Stack",
  "task-permitgmp": "Permit Submission & GMP / Procurement",
  "task-drawprocess": "Construction Administration & Draw Process",
  "task-gotomarket": "Branding & Leasing/Sales Execution",
  "task-closeout": "Punch List, Commissioning & Final Inspections",
  "task-operatingplan": "Property Operating & Asset Management Plan",
  "task-holdsell": "Stabilization / Refinance / Disposition Analysis",
  "dec-concept": "Proceed with the concept?",
  "dec-site": "Pursue this site? Enter site control / LOI?",
  "dec-criteria": "Does the opportunity meet investment criteria?",
  "dec-dd": "Proceed after due diligence?",
  "dec-close": "Close the acquisition?",
  "dec-plan": "Advance the plan / program?",
  "dec-entitlement": "Pursue / accept entitlement conditions?",
  "dec-design": "Approve design development?",
  "dec-capital": "Commit the capital stack?",
  "dec-authorize": "Authorize construction?",
  "dec-changes": "Approve changes / use contingency?",
  "dec-pricing": "Adjust pricing / marketing / leasing?",
  "dec-accept": "Accept completion / transition to operations?",
  "dec-opsplan": "Adjust the operating business plan?",
  "dec-exit": "Hold, refinance, or sell?"
};
