from .scoring import (
    ActivityConfig,
    CardConfig,
    CardFeedback,
    CardPlacement,
    CardResult,
    Configuration,
    Placement,
    PhaseEvaluation,
    RoundConfig,
    RoundResult,
    ScoreResult,
    TargetEvaluation,
    WeakestCard,
    WeakestMatch,
    classify,
    earned_for,
    score,
    score_targets,
)

__all__ = [
    # Phase-typed (backward compatible)
    "ActivityConfig",
    "Configuration",
    "Placement",
    "PhaseEvaluation",
    "CardFeedback",
    "WeakestMatch",
    "ScoreResult",
    "classify",
    "earned_for",
    "score",
    # Generic string-target core (multi-round)
    "CardConfig",
    "RoundConfig",
    "CardPlacement",
    "TargetEvaluation",
    "CardResult",
    "WeakestCard",
    "RoundResult",
    "score_targets",
]
